### ISSUE TITLE
File created, w/o TKey being inserted

### ISSUE THREAD

**Issue by SallSim** [quite/age-plugin-tkey#2]
If I run the command `age-plugin-tkey --generate --output my-identity` without having TKey connected to the computer I get the error `NewIdentity failed: GetPubKey failed: connect failed: DetectSerialPort failed: no TKey connected`. This is expected.

I then connect TKey to the computer and run `age-plugin-tkey --generate --output my-identity` again. I then receive another error: `OpenFile failed: open my-identity: file exists`.

Unnecessarily annoying.

**Comment by quite** [comment]
Yup I agree. Fixed.
